[metadata]
name = "nerdyman"
author = "nerdyman"
origin_url = "https://github.com/nerdyman/dotfiles/tree/main/home/.config/wezterm/colors/nerdyman.toml"

[colors]
foreground = "#ead8ff"
background = "#21182b"
cursor_bg = "#f783ac"
cursor_border = "#f783ac"
cursor_fg = "#1f1b2a"
selection_bg = "#f783ac"
selection_fg = "#1a172e"

ansi = [
	"#523c69",
	"#ff5462",
	"#bdff7b",
	"#ffda54",
	"#b3b3ff",
	"#e599f7",
	"#60f7ff",
	"#e1e1e6",
]

brights = [
	"#8c6ca0",
	"#fb5858",
	"#abf160",
	"#ffe066",
	"#a794ff",
	"#f783ac",
	"#87edf3",
	"#ffffff",
]

# [colors.indexed]
# 16 = "#d685af"
# 17 = "#d7827e"

[colors.tab_bar]
background = "rgba(0% 0% 0% 20%)"
inactive_tab_edge = "#ebe5df"
inactive_tab_edge_hover = "#ebe0df"

[colors.tab_bar.active_tab]
bg_color = "#a794ff"
fg_color = "#21182b"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "rgba(0% 0% 0% 25%)"
fg_color = "#b3b3ff"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

# [colors.tab_bar.inactive_tab_hover]
# bg_color = "#ebdfe4"
# fg_color = "#575279"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"

[colors.tab_bar.new_tab]
bg_color = "rgba(0% 0% 0% 25%)"
fg_color = "#b3b3ff"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

# [colors.tab_bar.new_tab_hover]
# bg_color = "#ebdfe4"
# fg_color = "#575279"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"
