[metadata]
name = "nerdyman"
author = "nerdyman"
origin_url = "https://github.com/nerdyman/dotfiles/tree/main/home/.config/wezterm/colors/nerdyman.toml"

# Colours are based on #a794ff

[colors]
foreground = "#c9bdff"
background = "#171424"
cursor_bg = "#ea94ff"
cursor_border = "#ea94ff"
cursor_fg = "#1f1b2a"
selection_bg = "#ea94ff"
selection_fg = "#1a172e"

ansi = [
	"#534d6f",
	"#ff6e7a",
	"#9bff7f",
	"#ffe571",
	"#b8a8ff",
	"#ea94ff",
	"#83eeff",
	"#e1dbff",
]

brights = [
	"#8a7cc9",
	"#ff7d8c",
	"#abf160",
	"#ffe066",
	"#a794ff",
	"#ea94ff",
	"#87edf3",
	"#ffffff",
]

[colors.indexed]
16 = "rgba(0, 0, 0, 0)"
17 = "#f00"

[colors.tab_bar]
background = "rgba(0% 0% 0% 20%)"
inactive_tab_edge = "#ebe5df"
inactive_tab_edge_hover = "#ebe0df"

[colors.tab_bar.active_tab]
bg_color = "#a794ff"
fg_color = "#21182b"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "rgba(0% 0% 0% 25%)"
fg_color = "#b8a8ff"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

# [colors.tab_bar.inactive_tab_hover]
# bg_color = "#ebdfe4"
# fg_color = "#575279"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"

[colors.tab_bar.new_tab]
bg_color = "rgba(0% 0% 0% 25%)"
fg_color = "#b8a8ff"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

# [colors.tab_bar.new_tab_hover]
# bg_color = "#ebdfe4"
# fg_color = "#575279"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"
