[metadata]
name = "nerdyman"
author = "nerdyman"
origin_url = "https://github.com/nerdyman/dotfiles/tree/main/home/.config/wezterm/themes/nerdyman.toml"

[colors]
foreground = "#ddcaff"
background = "#1f1b2a"
cursor_bg = "#f783ac"
cursor_border = "#f783ac"
cursor_fg = "#1f1b2a"
selection_bg = "#f783ac"
selection_fg = "#1a172e"

ansi = [
	"#464669",
	"#fb5858",
	"#abf160",
	"#ffe066",
	"#9e89fd",
	"#f783ac",
	"#87edf3",
	"#ffffff",
]

brights = [
	"#50507a",
	"#ff5e5e",
	"#c7fc91",
	"#ffeba5",
	"#b3b3ff",
	"#e599f7",
	"#a2f5f9",
	"#e1e1e6",
]

# [colors.indexed]
# 16 = "#d685af"
# 17 = "#d7827e"

# [colors.tab_bar]
# background = "#ebe5df"
# inactive_tab_edge = "#ebe5df"
# inactive_tab_edge_hover = "#ebe0df"

# [colors.tab_bar.active_tab]
# bg_color = "#a8a3b3"
# fg_color = "#faf4ed"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"

# [colors.tab_bar.inactive_tab]
# bg_color = "#ebe0df"
# fg_color = "#625c87"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"

# [colors.tab_bar.inactive_tab_hover]
# bg_color = "#ebdfe4"
# fg_color = "#575279"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"

# [colors.tab_bar.new_tab]
# bg_color = "#faf4ed"
# fg_color = "#625c87"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"

# [colors.tab_bar.new_tab_hover]
# bg_color = "#ebdfe4"
# fg_color = "#575279"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"
